jitterbunk/bunk/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^new_bunk$', views.CreateBunkView.as_view(), name='create'),
    url(r'^(?P<slug>[-\w\d]+)$', views.user_profile_view, name='detail'),
]

jitterbunk/jitterbunk/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('bunk.urls', namespace="bunk")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

jitterbunk/bunk/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    photo_url = models.URLField()
    slug = models.SlugField(unique=True, default="Reset")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.slug

class Bunk(models.Model):
    from_user = models.ForeignKey(UserProfile, on_delete=models.PROTECT, related_name="from_user")
    to_user = models.ForeignKey(UserProfile, on_delete=models.PROTECT, related_name="to_user")
    time_sent = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this bunk was sent.")

    def __str__(self):
        return (self.time_sent).strftime("%Y:%M:%D %H:%M:%S")

jitterbunk/bunk/forms.py
from django import forms

from .models import Bunk

class BunkCreateForm(forms.ModelForm):
    class Meta:
        model = Bunk
        fields = "__all__"

jitterbunk/bunk/views.py
from django.views import generic
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login

from .models import Bunk, UserProfile
from .forms import BunkCreateForm

class IndexView(generic.ListView):
    template_name = 'bunk/main_feed.html'
    context_object_name = 'bunk_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["users"] = UserProfile.objects.all()
        return context

    def get_queryset(self):
        """Return all bunks."""
        return Bunk.objects.order_by('-time_sent')[:20]

def user_profile_view(request, slug):
    user = UserProfile.objects.get(slug=slug)
    bunks_recieved = Bunk.objects.filter(to_user=user)
    bunks_sent = Bunk.objects.filter(from_user=user)
    all_bunks = bunks_recieved | bunks_sent
    context = {
        'user': user,
        'user_bunks': all_bunks.order_by('-time_sent')[:20]
    }
    return render(request, 'bunk/user_feed.html', context)

class CreateBunkView(generic.CreateView):
    model = Bunk
    fields = "__all__"

    def get_success_url(self):
        return reverse('bunk:index')

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
    else:
        reverse('bunk:login')

jitterbunk/bunk/templates/bunk/bunk_form.html
<h2>New bunk</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

jitterbunk/bunk/templates/bunk/index.html
{% if bunk_list %}
    <ul>
    {% for bunk in bunk_list %}
        <li>{{ bunk.from_user.user.username }} bunked {{ bunk.to_user.user.username }}!
            <small>{{ bunk.time_sent }}</small></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bunks yet!</p>
{% endif %}

jitterbunk/bunk/templates/bunk/main_feed.html
<h1>Last 20 Bunks</h1>

{% if bunk_list %}
    <ul>
    {% for bunk in bunk_list %}
        <li><a href="{% url 'bunk:detail' bunk.from_user %}">{{ bunk.from_user.user.username }}</a> bunked <a href="{% url 'bunk:detail' bunk.to_user %}">{{ bunk.to_user.user.username }}</a>!
            <small>{{ bunk.time_sent }}</small></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bunks yet!</p>
{% endif %}


<a href="{% url 'bunk:create' %}"><h1>Add a new bunk?</h1></a>

jitterbunk/bunk/templates/bunk/user_feed.html
<img src="{{user.photo_url}}" width="200" height="200" />

<h1>{{user}}'s Bunks</h1>

{% if user_bunks %}
    <ul>
    {% for bunk in user_bunks %}
        <li><a href="{% url 'bunk:detail' bunk.from_user %}">{{bunk.from_user.user.username}}</a> bunked <a href="{% url 'bunk:detail' bunk.to_user %}">{{bunk.to_user.user.username}}</a>!
        <small>{{bunk.time_sent}}</small></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bunks yet!</p>
{% endif %}